#!/usr/bin/env perl

use strict;
use warnings;

use File::Basename qw(basename);
use File::Spec;
use FindBin qw($Bin);

my $command = basename($0);
my $core = File::Spec->catfile( $Bin, '_dashboard-core' );
exec { $^X } $^X, $core, $command, @ARGV;
die "Unable to exec $core for $command: $!";

__END__

=pod

=head1 NAME

config - private built-in command wrapper for Developer Dashboard

=head1 SYNOPSIS

  dashboard config ...

=head1 DESCRIPTION

This private helper is staged under F<~/.developer-dashboard/cli/> so the
public C<dashboard> entrypoint can stay a thin switchboard.

=cut
