#!/usr/bin/env perl

use strict;
use warnings;

use FindBin qw($Bin);
use lib "$Bin/../lib";

use Developer::Dashboard::CLI::Query qw(run_query_command);

# main(@ARGV)
# Runs the XML query command for Developer Dashboard.
# Input: command-line arguments from @ARGV and optional STDIN.
# Output: prints the selected XML value, then exits.
run_query_command( command => 'xmlq', args => \@ARGV );

__END__

=pod

=head1 NAME

xmlq - XML query command for Developer Dashboard

=head1 SYNOPSIS

  dashboard xmlq [path] [file]

=head1 DESCRIPTION

This command provides XML extraction for Developer Dashboard.

=cut
